/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContextualBanner {
        "bannertitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TextField {
        "placeholder": string;
    }
    interface TheseusButton {
    }
}
declare global {
    interface HTMLContextualBannerElement extends Components.ContextualBanner, HTMLStencilElement {
    }
    var HTMLContextualBannerElement: {
        prototype: HTMLContextualBannerElement;
        new (): HTMLContextualBannerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {
    }
    var HTMLTextFieldElement: {
        prototype: HTMLTextFieldElement;
        new (): HTMLTextFieldElement;
    };
    interface HTMLTheseusButtonElement extends Components.TheseusButton, HTMLStencilElement {
    }
    var HTMLTheseusButtonElement: {
        prototype: HTMLTheseusButtonElement;
        new (): HTMLTheseusButtonElement;
    };
    interface HTMLElementTagNameMap {
        "contextual-banner": HTMLContextualBannerElement;
        "my-component": HTMLMyComponentElement;
        "text-field": HTMLTextFieldElement;
        "theseus-button": HTMLTheseusButtonElement;
    }
}
declare namespace LocalJSX {
    interface ContextualBanner {
        "bannertitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TextField {
        "placeholder"?: string;
    }
    interface TheseusButton {
    }
    interface IntrinsicElements {
        "contextual-banner": ContextualBanner;
        "my-component": MyComponent;
        "text-field": TextField;
        "theseus-button": TheseusButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "contextual-banner": LocalJSX.ContextualBanner & JSXBase.HTMLAttributes<HTMLContextualBannerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "text-field": LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
            "theseus-button": LocalJSX.TheseusButton & JSXBase.HTMLAttributes<HTMLTheseusButtonElement>;
        }
    }
}
