/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContextualBanner {
        "bannertitle"?: string;
    }
    interface DropDown {
    }
    interface TextField {
        "placeholder": string;
    }
    interface TheseusButton {
        "variant": string;
    }
    interface TheseusIcon {
        "variant": string;
    }
}
declare global {
    interface HTMLContextualBannerElement extends Components.ContextualBanner, HTMLStencilElement {
    }
    var HTMLContextualBannerElement: {
        prototype: HTMLContextualBannerElement;
        new (): HTMLContextualBannerElement;
    };
    interface HTMLDropDownElement extends Components.DropDown, HTMLStencilElement {
    }
    var HTMLDropDownElement: {
        prototype: HTMLDropDownElement;
        new (): HTMLDropDownElement;
    };
    interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {
    }
    var HTMLTextFieldElement: {
        prototype: HTMLTextFieldElement;
        new (): HTMLTextFieldElement;
    };
    interface HTMLTheseusButtonElement extends Components.TheseusButton, HTMLStencilElement {
    }
    var HTMLTheseusButtonElement: {
        prototype: HTMLTheseusButtonElement;
        new (): HTMLTheseusButtonElement;
    };
    interface HTMLTheseusIconElement extends Components.TheseusIcon, HTMLStencilElement {
    }
    var HTMLTheseusIconElement: {
        prototype: HTMLTheseusIconElement;
        new (): HTMLTheseusIconElement;
    };
    interface HTMLElementTagNameMap {
        "contextual-banner": HTMLContextualBannerElement;
        "drop-down": HTMLDropDownElement;
        "text-field": HTMLTextFieldElement;
        "theseus-button": HTMLTheseusButtonElement;
        "theseus-icon": HTMLTheseusIconElement;
    }
}
declare namespace LocalJSX {
    interface ContextualBanner {
        "bannertitle"?: string;
    }
    interface DropDown {
    }
    interface TextField {
        "placeholder"?: string;
    }
    interface TheseusButton {
        "variant"?: string;
    }
    interface TheseusIcon {
        "variant"?: string;
    }
    interface IntrinsicElements {
        "contextual-banner": ContextualBanner;
        "drop-down": DropDown;
        "text-field": TextField;
        "theseus-button": TheseusButton;
        "theseus-icon": TheseusIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "contextual-banner": LocalJSX.ContextualBanner & JSXBase.HTMLAttributes<HTMLContextualBannerElement>;
            "drop-down": LocalJSX.DropDown & JSXBase.HTMLAttributes<HTMLDropDownElement>;
            "text-field": LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
            "theseus-button": LocalJSX.TheseusButton & JSXBase.HTMLAttributes<HTMLTheseusButtonElement>;
            "theseus-icon": LocalJSX.TheseusIcon & JSXBase.HTMLAttributes<HTMLTheseusIconElement>;
        }
    }
}
